# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cnbi/dev/fesapps/fesjson

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cnbi/dev/fesapps/fesjson

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cnbi/dev/fesapps/fesjson/CMakeFiles /home/cnbi/dev/fesapps/fesjson/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cnbi/dev/fesapps/fesjson/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fescontrol

# Build rule for target.
fescontrol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fescontrol
.PHONY : fescontrol

# fast build rule for target.
fescontrol/fast:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/build
.PHONY : fescontrol/fast

#=============================================================================
# Target rules for targets named fesControl

# Build rule for target.
fesControl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fesControl
.PHONY : fesControl

# fast build rule for target.
fesControl/fast:
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/build
.PHONY : fesControl/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/main.cpp.s
.PHONY : main.cpp.s

src/Application.o: src/Application.cpp.o

.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Channel.o: src/Channel.cpp.o

.PHONY : src/Channel.o

# target to build an object file
src/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Channel.cpp.o
.PHONY : src/Channel.cpp.o

src/Channel.i: src/Channel.cpp.i

.PHONY : src/Channel.i

# target to preprocess a source file
src/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Channel.cpp.i
.PHONY : src/Channel.cpp.i

src/Channel.s: src/Channel.cpp.s

.PHONY : src/Channel.s

# target to generate assembly for a file
src/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/Channel.cpp.s
.PHONY : src/Channel.cpp.s

src/ConnectedApplication.o: src/ConnectedApplication.cpp.o

.PHONY : src/ConnectedApplication.o

# target to build an object file
src/ConnectedApplication.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/ConnectedApplication.cpp.o
.PHONY : src/ConnectedApplication.cpp.o

src/ConnectedApplication.i: src/ConnectedApplication.cpp.i

.PHONY : src/ConnectedApplication.i

# target to preprocess a source file
src/ConnectedApplication.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/ConnectedApplication.cpp.i
.PHONY : src/ConnectedApplication.cpp.i

src/ConnectedApplication.s: src/ConnectedApplication.cpp.s

.PHONY : src/ConnectedApplication.s

# target to generate assembly for a file
src/ConnectedApplication.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/ConnectedApplication.cpp.s
.PHONY : src/ConnectedApplication.cpp.s

src/FESJsonReader.o: src/FESJsonReader.cpp.o

.PHONY : src/FESJsonReader.o

# target to build an object file
src/FESJsonReader.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESJsonReader.cpp.o
.PHONY : src/FESJsonReader.cpp.o

src/FESJsonReader.i: src/FESJsonReader.cpp.i

.PHONY : src/FESJsonReader.i

# target to preprocess a source file
src/FESJsonReader.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESJsonReader.cpp.i
.PHONY : src/FESJsonReader.cpp.i

src/FESJsonReader.s: src/FESJsonReader.cpp.s

.PHONY : src/FESJsonReader.s

# target to generate assembly for a file
src/FESJsonReader.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESJsonReader.cpp.s
.PHONY : src/FESJsonReader.cpp.s

src/FESStimulator.o: src/FESStimulator.cpp.o

.PHONY : src/FESStimulator.o

# target to build an object file
src/FESStimulator.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESStimulator.cpp.o
.PHONY : src/FESStimulator.cpp.o

src/FESStimulator.i: src/FESStimulator.cpp.i

.PHONY : src/FESStimulator.i

# target to preprocess a source file
src/FESStimulator.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESStimulator.cpp.i
.PHONY : src/FESStimulator.cpp.i

src/FESStimulator.s: src/FESStimulator.cpp.s

.PHONY : src/FESStimulator.s

# target to generate assembly for a file
src/FESStimulator.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/FESStimulator.cpp.s
.PHONY : src/FESStimulator.cpp.s

src/GUI/GUIFESStimulator.o: src/GUI/GUIFESStimulator.cpp.o

.PHONY : src/GUI/GUIFESStimulator.o

# target to build an object file
src/GUI/GUIFESStimulator.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/GUI/GUIFESStimulator.cpp.o
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/src/GUI/GUIFESStimulator.cpp.o
.PHONY : src/GUI/GUIFESStimulator.cpp.o

src/GUI/GUIFESStimulator.i: src/GUI/GUIFESStimulator.cpp.i

.PHONY : src/GUI/GUIFESStimulator.i

# target to preprocess a source file
src/GUI/GUIFESStimulator.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/GUI/GUIFESStimulator.cpp.i
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/src/GUI/GUIFESStimulator.cpp.i
.PHONY : src/GUI/GUIFESStimulator.cpp.i

src/GUI/GUIFESStimulator.s: src/GUI/GUIFESStimulator.cpp.s

.PHONY : src/GUI/GUIFESStimulator.s

# target to generate assembly for a file
src/GUI/GUIFESStimulator.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/GUI/GUIFESStimulator.cpp.s
	$(MAKE) -f CMakeFiles/fesControl.dir/build.make CMakeFiles/fesControl.dir/src/GUI/GUIFESStimulator.cpp.s
.PHONY : src/GUI/GUIFESStimulator.cpp.s

src/IncrementerFactory.o: src/IncrementerFactory.cpp.o

.PHONY : src/IncrementerFactory.o

# target to build an object file
src/IncrementerFactory.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/IncrementerFactory.cpp.o
.PHONY : src/IncrementerFactory.cpp.o

src/IncrementerFactory.i: src/IncrementerFactory.cpp.i

.PHONY : src/IncrementerFactory.i

# target to preprocess a source file
src/IncrementerFactory.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/IncrementerFactory.cpp.i
.PHONY : src/IncrementerFactory.cpp.i

src/IncrementerFactory.s: src/IncrementerFactory.cpp.s

.PHONY : src/IncrementerFactory.s

# target to generate assembly for a file
src/IncrementerFactory.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/IncrementerFactory.cpp.s
.PHONY : src/IncrementerFactory.cpp.s

src/LinearIncrementer.o: src/LinearIncrementer.cpp.o

.PHONY : src/LinearIncrementer.o

# target to build an object file
src/LinearIncrementer.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/LinearIncrementer.cpp.o
.PHONY : src/LinearIncrementer.cpp.o

src/LinearIncrementer.i: src/LinearIncrementer.cpp.i

.PHONY : src/LinearIncrementer.i

# target to preprocess a source file
src/LinearIncrementer.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/LinearIncrementer.cpp.i
.PHONY : src/LinearIncrementer.cpp.i

src/LinearIncrementer.s: src/LinearIncrementer.cpp.s

.PHONY : src/LinearIncrementer.s

# target to generate assembly for a file
src/LinearIncrementer.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/LinearIncrementer.cpp.s
.PHONY : src/LinearIncrementer.cpp.s

src/MovementAuthorizer.o: src/MovementAuthorizer.cpp.o

.PHONY : src/MovementAuthorizer.o

# target to build an object file
src/MovementAuthorizer.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/MovementAuthorizer.cpp.o
.PHONY : src/MovementAuthorizer.cpp.o

src/MovementAuthorizer.i: src/MovementAuthorizer.cpp.i

.PHONY : src/MovementAuthorizer.i

# target to preprocess a source file
src/MovementAuthorizer.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/MovementAuthorizer.cpp.i
.PHONY : src/MovementAuthorizer.cpp.i

src/MovementAuthorizer.s: src/MovementAuthorizer.cpp.s

.PHONY : src/MovementAuthorizer.s

# target to generate assembly for a file
src/MovementAuthorizer.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/MovementAuthorizer.cpp.s
.PHONY : src/MovementAuthorizer.cpp.s

src/SetterAction.o: src/SetterAction.cpp.o

.PHONY : src/SetterAction.o

# target to build an object file
src/SetterAction.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/SetterAction.cpp.o
.PHONY : src/SetterAction.cpp.o

src/SetterAction.i: src/SetterAction.cpp.i

.PHONY : src/SetterAction.i

# target to preprocess a source file
src/SetterAction.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/SetterAction.cpp.i
.PHONY : src/SetterAction.cpp.i

src/SetterAction.s: src/SetterAction.cpp.s

.PHONY : src/SetterAction.s

# target to generate assembly for a file
src/SetterAction.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/SetterAction.cpp.s
.PHONY : src/SetterAction.cpp.s

src/StimulationAction.o: src/StimulationAction.cpp.o

.PHONY : src/StimulationAction.o

# target to build an object file
src/StimulationAction.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationAction.cpp.o
.PHONY : src/StimulationAction.cpp.o

src/StimulationAction.i: src/StimulationAction.cpp.i

.PHONY : src/StimulationAction.i

# target to preprocess a source file
src/StimulationAction.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationAction.cpp.i
.PHONY : src/StimulationAction.cpp.i

src/StimulationAction.s: src/StimulationAction.cpp.s

.PHONY : src/StimulationAction.s

# target to generate assembly for a file
src/StimulationAction.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationAction.cpp.s
.PHONY : src/StimulationAction.cpp.s

src/StimulationActionFactory.o: src/StimulationActionFactory.cpp.o

.PHONY : src/StimulationActionFactory.o

# target to build an object file
src/StimulationActionFactory.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationActionFactory.cpp.o
.PHONY : src/StimulationActionFactory.cpp.o

src/StimulationActionFactory.i: src/StimulationActionFactory.cpp.i

.PHONY : src/StimulationActionFactory.i

# target to preprocess a source file
src/StimulationActionFactory.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationActionFactory.cpp.i
.PHONY : src/StimulationActionFactory.cpp.i

src/StimulationActionFactory.s: src/StimulationActionFactory.cpp.s

.PHONY : src/StimulationActionFactory.s

# target to generate assembly for a file
src/StimulationActionFactory.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/StimulationActionFactory.cpp.s
.PHONY : src/StimulationActionFactory.cpp.s

src/TimeLimitedAction.o: src/TimeLimitedAction.cpp.o

.PHONY : src/TimeLimitedAction.o

# target to build an object file
src/TimeLimitedAction.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/TimeLimitedAction.cpp.o
.PHONY : src/TimeLimitedAction.cpp.o

src/TimeLimitedAction.i: src/TimeLimitedAction.cpp.i

.PHONY : src/TimeLimitedAction.i

# target to preprocess a source file
src/TimeLimitedAction.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/TimeLimitedAction.cpp.i
.PHONY : src/TimeLimitedAction.cpp.i

src/TimeLimitedAction.s: src/TimeLimitedAction.cpp.s

.PHONY : src/TimeLimitedAction.s

# target to generate assembly for a file
src/TimeLimitedAction.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/TimeLimitedAction.cpp.s
.PHONY : src/TimeLimitedAction.cpp.s

src/interfaces/CcCoreInstance.o: src/interfaces/CcCoreInstance.cpp.o

.PHONY : src/interfaces/CcCoreInstance.o

# target to build an object file
src/interfaces/CcCoreInstance.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/CcCoreInstance.cpp.o
.PHONY : src/interfaces/CcCoreInstance.cpp.o

src/interfaces/CcCoreInstance.i: src/interfaces/CcCoreInstance.cpp.i

.PHONY : src/interfaces/CcCoreInstance.i

# target to preprocess a source file
src/interfaces/CcCoreInstance.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/CcCoreInstance.cpp.i
.PHONY : src/interfaces/CcCoreInstance.cpp.i

src/interfaces/CcCoreInstance.s: src/interfaces/CcCoreInstance.cpp.s

.PHONY : src/interfaces/CcCoreInstance.s

# target to generate assembly for a file
src/interfaces/CcCoreInstance.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/CcCoreInstance.cpp.s
.PHONY : src/interfaces/CcCoreInstance.cpp.s

src/interfaces/ClLoopInstance.o: src/interfaces/ClLoopInstance.cpp.o

.PHONY : src/interfaces/ClLoopInstance.o

# target to build an object file
src/interfaces/ClLoopInstance.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClLoopInstance.cpp.o
.PHONY : src/interfaces/ClLoopInstance.cpp.o

src/interfaces/ClLoopInstance.i: src/interfaces/ClLoopInstance.cpp.i

.PHONY : src/interfaces/ClLoopInstance.i

# target to preprocess a source file
src/interfaces/ClLoopInstance.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClLoopInstance.cpp.i
.PHONY : src/interfaces/ClLoopInstance.cpp.i

src/interfaces/ClLoopInstance.s: src/interfaces/ClLoopInstance.cpp.s

.PHONY : src/interfaces/ClLoopInstance.s

# target to generate assembly for a file
src/interfaces/ClLoopInstance.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClLoopInstance.cpp.s
.PHONY : src/interfaces/ClLoopInstance.cpp.s

src/interfaces/ClTobiIdInstance.o: src/interfaces/ClTobiIdInstance.cpp.o

.PHONY : src/interfaces/ClTobiIdInstance.o

# target to build an object file
src/interfaces/ClTobiIdInstance.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClTobiIdInstance.cpp.o
.PHONY : src/interfaces/ClTobiIdInstance.cpp.o

src/interfaces/ClTobiIdInstance.i: src/interfaces/ClTobiIdInstance.cpp.i

.PHONY : src/interfaces/ClTobiIdInstance.i

# target to preprocess a source file
src/interfaces/ClTobiIdInstance.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClTobiIdInstance.cpp.i
.PHONY : src/interfaces/ClTobiIdInstance.cpp.i

src/interfaces/ClTobiIdInstance.s: src/interfaces/ClTobiIdInstance.cpp.s

.PHONY : src/interfaces/ClTobiIdInstance.s

# target to generate assembly for a file
src/interfaces/ClTobiIdInstance.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/ClTobiIdInstance.cpp.s
.PHONY : src/interfaces/ClTobiIdInstance.cpp.s

src/interfaces/SerialPort.o: src/interfaces/SerialPort.cpp.o

.PHONY : src/interfaces/SerialPort.o

# target to build an object file
src/interfaces/SerialPort.cpp.o:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/SerialPort.cpp.o
.PHONY : src/interfaces/SerialPort.cpp.o

src/interfaces/SerialPort.i: src/interfaces/SerialPort.cpp.i

.PHONY : src/interfaces/SerialPort.i

# target to preprocess a source file
src/interfaces/SerialPort.cpp.i:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/SerialPort.cpp.i
.PHONY : src/interfaces/SerialPort.cpp.i

src/interfaces/SerialPort.s: src/interfaces/SerialPort.cpp.s

.PHONY : src/interfaces/SerialPort.s

# target to generate assembly for a file
src/interfaces/SerialPort.cpp.s:
	$(MAKE) -f CMakeFiles/fescontrol.dir/build.make CMakeFiles/fescontrol.dir/src/interfaces/SerialPort.cpp.s
.PHONY : src/interfaces/SerialPort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... fescontrol"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fesControl"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Channel.o"
	@echo "... src/Channel.i"
	@echo "... src/Channel.s"
	@echo "... src/ConnectedApplication.o"
	@echo "... src/ConnectedApplication.i"
	@echo "... src/ConnectedApplication.s"
	@echo "... src/FESJsonReader.o"
	@echo "... src/FESJsonReader.i"
	@echo "... src/FESJsonReader.s"
	@echo "... src/FESStimulator.o"
	@echo "... src/FESStimulator.i"
	@echo "... src/FESStimulator.s"
	@echo "... src/GUI/GUIFESStimulator.o"
	@echo "... src/GUI/GUIFESStimulator.i"
	@echo "... src/GUI/GUIFESStimulator.s"
	@echo "... src/IncrementerFactory.o"
	@echo "... src/IncrementerFactory.i"
	@echo "... src/IncrementerFactory.s"
	@echo "... src/LinearIncrementer.o"
	@echo "... src/LinearIncrementer.i"
	@echo "... src/LinearIncrementer.s"
	@echo "... src/MovementAuthorizer.o"
	@echo "... src/MovementAuthorizer.i"
	@echo "... src/MovementAuthorizer.s"
	@echo "... src/SetterAction.o"
	@echo "... src/SetterAction.i"
	@echo "... src/SetterAction.s"
	@echo "... src/StimulationAction.o"
	@echo "... src/StimulationAction.i"
	@echo "... src/StimulationAction.s"
	@echo "... src/StimulationActionFactory.o"
	@echo "... src/StimulationActionFactory.i"
	@echo "... src/StimulationActionFactory.s"
	@echo "... src/TimeLimitedAction.o"
	@echo "... src/TimeLimitedAction.i"
	@echo "... src/TimeLimitedAction.s"
	@echo "... src/interfaces/CcCoreInstance.o"
	@echo "... src/interfaces/CcCoreInstance.i"
	@echo "... src/interfaces/CcCoreInstance.s"
	@echo "... src/interfaces/ClLoopInstance.o"
	@echo "... src/interfaces/ClLoopInstance.i"
	@echo "... src/interfaces/ClLoopInstance.s"
	@echo "... src/interfaces/ClTobiIdInstance.o"
	@echo "... src/interfaces/ClTobiIdInstance.i"
	@echo "... src/interfaces/ClTobiIdInstance.s"
	@echo "... src/interfaces/SerialPort.o"
	@echo "... src/interfaces/SerialPort.i"
	@echo "... src/interfaces/SerialPort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

